### PR TITLE
Kdm e39

### PR DESCRIPTION
**Pull request by kmalinich**

### CODE REVIEW

**Comment by botanika** [comment]
Can you maybe tell me how to run this? I always get 3 dots or syntax error. Sorry I'm very beginner and i like your project. I'm running a raspberry pi 3 with the latest raspbian and Node. And one more question, which interface are you using? Tank you very much for your help.

**Comment by kmalinich** [comment]
Can you post a snippet of what you're seeing? 

Personally I'm using Rolf Resler's USB IBUS interface:
http://www.reslers.de/IBUS/

You can also use a USB cable that is compatible with INPA/NCSexpert/etc, and connect the IBUS/KBUS line to pin OBD pin 7, as detailed at the end of the first post in this thread:

https://www.bimmerforums.com/forum/showthread.php?1505990-My-DIS-INPA-SSS-CARSOFT-NAVCODER-Interface

**Comment by botanika** [comment]
Hey, tanks for your fast reply. I managed to get it run via cd to folder then node then .Load xyz. Is that the correct way? And I got one more question. I also got the resler stick and it worked with navcoder but i cant get it working on the raspberry. Is there any chance u can tell me how to configure it? I read it had something with usb0 and baud rate which i wasn't able to change. Is there a tutorial or something. I'm googling without any good result. Would be nice if you could help me one more. Thank you very much for your help.

**Comment by kmalinich** [comment]
Look, I'm not 100% sure how to say this, but I don't really recommend running this project repo straight up. You should fork it or start your own thing. I actually consulted with someone and realized I had to add a license absolving me of responsibility, because there could be dangerous real-life consequences to this project, like lights not working at night, airbags going off, etc. It's not that I don't want to help - but you have to 100% completely and fully understand what you're doing with this code and this project, and if I help you get it running too much - well, there's a solid chance that you don't understand all of it's moving parts, and you could quite literally hurt yourself, and potentially end up in the hospital.

**Comment by botanika** [comment]
Thx for your answer. I'm working at BMW development and i also have licence to operate at all BMW prototype's. if there is a malfunction in the software i know to dedect and handle the car safe. I got license to operate with BMW's beta software's and airbags, but i don't understand how to manage your project on the old bmw models and how should i manage it with raspberry. It's my hobby and i want to play around with it to get started. I can understand your​ doubt but please just give me a way to get it.

**Pull request merged**
